name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm ci
        working-directory: integrationcontinue

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run lint
        run: npm run lint
        working-directory: integrationcontinue

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: npm test
        working-directory: integrationcontinue

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build
        run: npm run build
        working-directory: integrationcontinue

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create release
        run: npx --yes release-it --ci
        working-directory: integrationcontinue

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Deploy application
        run: echo "Deploy step (to be implemented)"
        working-directory: integrationcontinue

