name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

  validate:
        runs-on: ubuntu-latest
        needs: install
        steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
            node-version: 'latest'
        
         - name: Install dependencies
           run: npm ci --cache .npm --prefer-offline

         - name: Run lint
           run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
      run: npm ci

      - name: Run unit tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build application
        run: npm run build

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create release
        run: npx --yes release-it --ci

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Deploy application
        run: echo "Deploy step (to be implemented)"
