name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: integrationcontinue/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('integrationcontinue/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies with cache
        run: npm ci --cache .npm --prefer-offline
      

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
       

      - name: Run lint
        run: npm run lint
       

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
        

      - name: Run tests
        run: npm test
        

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run build
        run: npm run build
        

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create release
        run: npx --yes release-it --ci
        

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Deploy application
        run: echo "Deploy step (to be implemented)"
        

